version: '3'

services:

  #service parse-server
  parse-server:
    container_name: parse-server
    image: barakbd/parse-server:test
    env_file: #not really needed as docker compose looks for .env by default
      - .env
    environment: 
      NODE_ENV: ${NODE_ENV}
    # volumes: 
      # - ./cloud:/parse-server/cloud
      # - ./config:parse-server/config
    ports:
      - 1337:1337
      # long syntax
      # - target: ${PORT}
      #   published: ${PORT}
      #   protocol: tcp
      #   mode: host
    networks:
      - backend
    depends_on:
      - mongo
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:1337"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # deploy:
    #   replicas: 2
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    # restart_policy:
    #   condition: on-failure
    #   delay: 5s
    #   max_attempts: 3
    #   window: 120s
    # entrypoint: ["npm", "run", "debug"] # overwrite entrypoint
    # build: . # if build arg not present, it will try to pull from registry

  #service mongo
  mongo:
    container_name: mongo-3.6
    image: mongo:3.6
    env_file:
      - .env
    ports:
      - 27018:27017
    # volumes:
    #   - ./db:/data/db
    networks:
      - backend



# sudo docker-compose up --force-recreate



# sudo docker run -it --rm --name mongo-3.6 \
# --env-file .env \
# -v $(pwd)/db:/data/db \
# -p 27018:27017 \
# mongo:3.6


networks:
  backend:

# sudo docker-compose up --force-recreate
