version: '3.2'

services:

  #service parse-server
  parse-server:
    container_name: parse-server
    image: barakbd/parse-server:test
    env_file: #not really needed as docker compose looks for .env by default
      - .env
    environment: 
      NODE_ENV: ${NODE_ENV}
    # volumes: 
      # - ./cloud:/parse-server/cloud
      # - ./config:parse-server/config
    ports:
      - 1337:1337
      # long syntax
      # - target: ${PORT}
      #   published: ${PORT}
      #   protocol: tcp
      #   mode: host
    networks:
      - backend
    depends_on:
      - mongo
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:1337"]
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s
    # deploy:
    #   replicas: 2
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    # restart_policy:
    #   condition: on-failure
    #   delay: 5s
    #   max_attempts: 3
    #   window: 120s
    # entrypoint: ["npm", "run", "debug"] # overwrite entrypoint
    # build: . # if build arg not present, it will try to pull from registry

  #service mongo
  mongo:
    container_name: mongo-3.6
    image: mongo:3.6
    env_file:
      - .env
    ports:
      # - 27019:27017
      - target: 27017 # inside container
        published: 27018
        protocol: tcp # tcp / udp
        mode: ingress # use ingress for swarm load balancing

    volumes:
      # - ./mongo/data/db:/data/db
      - ./mongo/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
      - ./mongo/scripts:/scripts/
    networks:
      - backend

# docker run -it --rm --name mongo-3.6 --env-file .env -p 27018:27017 -v $(pwd)/mongo/docker-entrypoint-initdb:/docker-entrypoint-initdb.d -v $(pwd)/mongo/scripts:/scripts mongo:3.6


networks:
  backend: